version: '3.5'
services:
    # RabbitMQ
    host_rmq:
        image: rabbitmq:3.7.14-management
        container_name: host_rmq
        ports:
            # RabbitMQ server
            - 5672:5672
            # RabbitMQ web site management http://localhost:15672 (guest:guest)
            - 15672:15672
    # Redis
    host_redis:
        container_name: host_redis
        image: 'bitnami/redis:latest'
        port: 
            - 6379:6379
        expose:
            - 6379
        #volumes:
            # redis persistence
            #- ./host_redis/data:/bitnami/redis/data
        environment:
            - ALLOW_EMPTY_PASSWORD=yes
    # PHP
    host_php:
        container_name: host_php
        build: ./host_php/docker
        ports:
            # web page http://localhost:3001
            - 3001:80
        volumes:
            - ./host_php/src:/var/www/host_php
            - ./host_php/docker/php.ini:/usr/local/etc/php/conf.d/custom.ini
            - ./host_php/docker/apache_host_php.conf:/etc/apache2/sites-enabled/host_php.conf
        depends_on:
            - host_rmq
            - host_redis
        environment:
            - MQ_HOST=host_rmq
            - MQ_QUEUE=hello
            - MQ_PORT=5672
            - MQ_USER=guest
            - MQ_PASSWORD=guest
            - HOST=host_php
            - REDIS_HOST=host_redis
            - REDIS_PORT=6379
    # NodeJS
    host_nodejs:
        container_name: host_nodejs
        build: ./host_nodejs/docker
        ports:
            # db web page http://localhost:3002
            - 3002:80
            # db json server http://localhost:3012
            - 3012:3000
        expose:
            - 3000
        depends_on:
            - host_rmq
            - host_redis
        environment:
            - WEB_PORT=80
            - WEB_HOST=0.0.0.0
            - MQ_URL=amqp://host_rmq
            - MQ_QUEUE=hello
            - HOST=host_nodejs
            - REDIS_HOST=host_redis
            - REDIS_PORT=6379
        volumes:
            - ./host_nodejs/src/server:/app/server