version: '3.5'
services:
    host_rmq:
        image: rabbitmq:3.7.14-management
        ports:
            - 5672:5672
            - 15672:15672
    host1:
        container_name: host1
        build: ./host1/docker
        ports:
            - 3001:80
        volumes:
            - ./host1/src:/var/www/host1
            - ./host1/docker/php.ini:/usr/local/etc/php/conf.d/custom.ini
            - ./host1/docker/apache_host1.conf:/etc/apache2/sites-enabled/host1.conf
#     host2:
#        container_name: host2
#        image:
#        ports:
#            - "3002:3002"
#        volumes:
#             - ../hosts2/:/var/www/host2
