version: '3.5'
services:
    host_rmq:
        image: rabbitmq:3.7.14-management
        container_name: host_rmq
        ports:
            - 5672:5672
            - 15672:15672
    host1:
        container_name: host1
        build: ./host1/docker
        ports:
            - 3001:80
        volumes:
            - ./host1/src:/var/www/host1
            - ./host1/docker/php.ini:/usr/local/etc/php/conf.d/custom.ini
            - ./host1/docker/apache_host1.conf:/etc/apache2/sites-enabled/host1.conf
    host2:
        container_name: host2
        build: ./host2/docker
        ports:
            - 3002:80
            - 3012:3000
        environment:
            - WEB_PORT=80
            - WEB_HOST=0.0.0.0
            - MQ_URL=amqp://host_rmq
            - MQ_QUEUE=hello
            - DB_HOST=0.0.0.0
            - DB_PORT=3000
            - DB_FILE=/app/data/db/db.json
            - HOST=host2
        volumes:
            - ./host2/src/server:/app/server
            - ./host2/data:/app/data