version: '3.5'
services:
    host_rmq:
        image: rabbitmq:3.7.14-management
        ports:
            - 5672:5672
            - 15672:15672
    host1:
        container_name: host1
        build: ./host1
        ports:
            - "3001:3001"
        volumes:
            - ../host1/:/var/www/host1
#     host2:
#        container_name: host2
#        image:
#        ports:
#            - "3002:3002"
#        volumes:
#             - ../hosts2/:/var/www/host2
